import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api, { assetUrl } from "../lib/api";

const money = value => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", maximumFractionDigits: 0 }).format(value);

export default function ProductPage() {
  const { slug } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [colorIndex, setColorIndex] = useState(0); const [imageIndex, setImageIndex] = useState(0);
  useEffect(() => { setData(null); setColorIndex(0); setImageIndex(0); api.get(`/catalog/products/${slug}`).then(response => setData(response.data)).catch(error => setError(error.response?.data?.message || "Unable to load product.")); }, [slug]);
  const color = data?.colors?.[colorIndex]; const images = color?.images || []; const discount = useMemo(() => data?.product.compareAtPrice ? Math.round((1-data.product.price/data.product.compareAtPrice)*100) : 0, [data]);
  if (error) return <main className="section-shell py-24"><h1 className="text-4xl font-light">Product unavailable</h1><p className="mt-4 text-slate-500">{error}</p></main>;
  if (!data) return <main className="section-shell py-24"><div className="grid gap-12 lg:grid-cols-2"><div className="h-[520px] animate-pulse rounded-[2rem] bg-slate-100" /><div className="space-y-5 pt-8"><div className="h-8 animate-pulse rounded bg-slate-100"/><div className="h-16 animate-pulse rounded bg-slate-100"/></div></div></main>;
  const { product, colors } = data;
  return <main className="site-soft-band pb-24"><div className="section-shell py-8"><nav className="text-sm text-slate-400"><Link to="/">Home</Link><span className="mx-2">/</span><Link to={`/categories/${product.category.slug}`}>{product.category.name}</Link><span className="mx-2">/</span><span className="text-slate-700">{product.name}</span></nav>
    <div className="mt-8 grid gap-12 lg:grid-cols-[1.1fr_.9fr]">
      <section><div className="flex h-[480px] items-center justify-center rounded-[2rem] bg-slate-50 p-8 md:h-[620px]">{images[imageIndex] ? <img src={assetUrl(images[imageIndex])} alt={`${product.name} in ${color?.name}`} className="h-full w-full object-contain" /> : <p className="text-slate-400">No image available</p>}</div>{images.length > 1 ? <div className="mt-4 flex gap-3 overflow-x-auto">{images.map((image, index) => <button key={image} onClick={() => setImageIndex(index)} className={`h-24 w-24 shrink-0 rounded-xl border bg-white p-2 ${index === imageIndex ? "border-emerald-700 ring-2 ring-emerald-100" : "border-slate-200"}`}><img src={assetUrl(image)} alt="" className="h-full w-full object-contain" /></button>)}</div> : null}</section>
      <section className="py-4 lg:py-8"><p className="text-xs font-bold uppercase tracking-[0.35em] text-emerald-700">{product.category.name}</p><h1 className="mt-4 text-4xl font-light tracking-[-0.045em] text-slate-950 md:text-6xl">{product.name}</h1>{product.shortDescription ? <p className="mt-5 text-base leading-8 text-slate-600">{product.shortDescription}</p> : null}<div className="mt-8 flex flex-wrap items-center gap-3"><strong className="text-3xl text-slate-950">{money(product.price)}</strong>{product.compareAtPrice ? <><span className="text-lg text-slate-400 line-through">{money(product.compareAtPrice)}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-700">{discount}% off</span></> : null}</div>
        {colors.length ? <div className="mt-9"><p className="text-sm font-bold text-slate-800">Color: <span className="font-normal">{color?.name}</span></p><div className="mt-4 flex max-w-full flex-wrap gap-3">{colors.map((item, index) => <button key={item.id} type="button" title={item.name} aria-pressed={index === colorIndex} onClick={() => { setColorIndex(index); setImageIndex(0); }} className={`flex items-center gap-2 rounded-full border px-4 py-2.5 text-sm font-semibold transition ${index === colorIndex ? "border-emerald-700 bg-emerald-50 text-emerald-900 ring-2 ring-emerald-100" : "border-slate-200 bg-white text-slate-600 hover:border-slate-400"}`}><span className="relative h-6 w-6 rounded-full border-2 border-white shadow-[0_0_0_1px_rgba(100,116,139,0.35)]" style={{ backgroundColor: item.hexCode || "#ddd" }}>{index === colorIndex ? <span className="absolute inset-0 flex items-center justify-center text-[10px] font-black text-white [text-shadow:0_1px_2px_rgba(0,0,0,0.85)]">✓</span> : null}</span>{item.name}</button>)}</div></div> : null}
        <div className="mt-9 rounded-2xl border border-slate-200 p-5"><p className={`font-bold ${product.stockQuantity > 0 ? "text-emerald-700" : "text-red-600"}`}>{product.stockQuantity > 0 ? "In stock" : "Currently out of stock"}</p><p className="mt-2 text-sm leading-6 text-slate-500">Contact LuckyZone to confirm availability and place your order.</p></div>{product.description ? <div className="mt-9 border-t border-slate-200 pt-7"><h2 className="text-lg font-bold text-slate-950">Product details</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{product.description}</p></div> : null}
      </section>
    </div></div></main>;
}
